Skills update
Zenika/skillZ pull request #169
Opened 2022-07-11 14:23 UTC by ZenikAdrien

2022-07-11 17:20 UTC, pierre-nicoli approved these changes

2022-07-11 17:20 UTC, pierre-nicoli approved these changes

2022-07-11 17:20 UTC, pierre-nicoli approved these changes

2022-07-11 17:22 UTC, pierre-nicoli approved these changes

2022-07-12 15:39 UTC, pierre-nicoli requested changes
Warning sur ligne 485 de 07-skillTopic.sql

2022-07-13 07:01 UTC, ZenikAdrien commented
je termine / mets à jour ce soir

2022-07-15 12:04 UTC, pierre-nicoli approved these changes

2022-07-17 12:23 UTC, merged