:fire: delete useless request and add result number on search page
Zenika/skillZ pull request #239
Opened 2022-09-26 16:04 UTC by MailyLehoux

fix #235

2022-09-27 07:28 UTC, benjaminbrgs reviewed
Really nice to have a count 👌🏼

I suggest to add an icon (like this one `BsFillPersonCheckFill` or another) next to the count on each skill to better understand what does the count mean.

Also, I don't know if it is wanted but when I search for a skill that which is not noted, it doesn't appear ?

2022-09-27 08:44 UTC, MailyLehoux commented
@benjaminbrgs the icon is a good idea

Yes I don't really know. I've ntoiced that yesterday. It was an old request for this search, so I kept it. I think it will be very rare that anyone note a skill on production env, so I didn't changed that. do you think it's annoying? I don't really have an opinion on it

2022-09-27 08:55 UTC, benjaminbrgs commented
@MailyLehoux I don't have too.. We can ignore this now, but keep it in mind if it's annoying for someone else in the future

2022-09-27 14:40 UTC, benjaminbrgs requested changes
Suggest this to horizontally align the number and the icon

<img width="243" alt="image" src="https://user-images.githubusercontent.com/20949060/192557308-c6c4ed25-ea2e-4aae-9318-1f6a850545b6.png">

To

<img width="243" alt="image" src="https://user-images.githubusercontent.com/20949060/192557410-14be2e01-9f87-44dc-9767-8bb0c0c76731.png">

2022-09-27 14:40 UTC, benjaminbrgs commented on src/components/SkillPanel.tsx
>                </div>
```suggestion
                <span>{count}</span>
                <BsFillPersonCheckFill />
```

2022-09-27 14:40 UTC, benjaminbrgs commented on src/components/SkillPanel.tsx
>              <div className="flex flex-row justify-around rounded-full w-16 px-1 py-1 bg-light-med dark:bg-dark-med">
```suggestion
            <div className="flex flex-row items-center justify-around rounded-full w-16 px-1 py-1 bg-light-med dark:bg-dark-med">
```

2022-09-28 08:02 UTC, MailyLehoux commented
thanks @benjaminbrgs looks better like this :+1:

2022-09-28 08:03 UTC, benjaminbrgs approved these changes

2022-09-28 12:28 UTC, merged