:green_heart: add eslint in ci
Zenika/skillZ pull request #327
Opened 2022-11-09 14:12 UTC by MailyLehoux

2022-11-10 09:07 UTC, PierreBrethes commented on src/components/CustomSelect.tsx
> +  keyFn: (x: any) => string; // eslint-disable-line no-unused-vars
Faudrait voir si il n'y a pas une vrai correction à la place de l'exception lint

2022-11-14 07:57 UTC, benjaminbrgs requested changes
The `next build` command already includes the eslint process.
Is it necessary to add this step a second time ?

2022-11-14 08:16 UTC, PierreBrethes commented
> The `next build` command already includes the eslint process. Is it necessary to add this step a second time ?
> 
> Otherwise, this PR is welcome to fix some eslint errors

This make sure that when you push code, it's clean. I think this is good for the quality code
And it takes few seconds

2022-11-14 08:31 UTC, MailyLehoux commented
> The `next build` command already includes the eslint process. Is it necessary to add this step a second time ?
> 
> Otherwise, this PR is welcome to fix some eslint errors

We had the basic eslint, I've added also some rules. And the eslint tests weren't on ci jobs. I don't think that eslint was enclenched at each push

2022-11-14 08:42 UTC, benjaminbrgs commented
> > The `next build` command already includes the eslint process. Is it necessary to add this step a second time ?
> > Otherwise, this PR is welcome to fix some eslint errors
> 
> We had the basic eslint, I've added also some rules. And the eslint tests weren't on ci jobs. I don't think that eslint was enclenched at each push

> This make sure that when you push code, it's clean. I think this is good for the quality code And it takes few seconds


I agree with adding some rules 👍🏻 
I mean, is it not a duplicate to add a eslint step in job as it is already running in another step (see https://app.circleci.com/pipelines/github/Zenika/skillZ/956/workflows/815b382d-6e7a-43b0-a7c3-a27a16637fc4/jobs/4817?invite=true#step-107-213) ?

2022-11-14 09:16 UTC, MailyLehoux commented
Indeed ! I didn't noticed that runs in next build. it looks like it don't take in account the new rules with this way. Maybe should we delete the eslint step from build ? And keep the eslint job.  For me it's clearer

2022-11-14 10:17 UTC, benjaminbrgs commented
> Indeed ! I didn't noticed that runs in next build. it looks like it don't take in account the new rules with this way. Maybe should we delete the eslint step from build ? And keep the eslint job. For me it's clearer

Agree with this proposal, it will be clearer

2022-11-14 14:33 UTC, benjaminbrgs approved these changes
Nice job 💪🏼

2022-11-14 14:33 UTC, benjaminbrgs commented on src/components/BotNotifications.tsx
> +  t: (path: string) => string /* eslint-disable-line no-unused-vars*/;
```suggestion
  t: (path: string) => string;
```

2022-11-15 08:29 UTC, MailyLehoux commented on src/components/BotNotifications.tsx
> +  t: (path: string) => string /* eslint-disable-line no-unused-vars*/;
Oops I missed this, nice catch thanks :+1:

2022-11-15 09:46 UTC, merged