WIP Feat/global search bar
Zenika/skillZ pull request #558
Opened 2023-02-13 14:44 UTC by MailyLehoux

resolve #537

2023-02-14 10:49 UTC, MailyLehoux commented
will be weird to test : according to #553 we can see the results of all the skills that are already noted. But for the search I used  the skills list

2023-02-14 13:17 UTC, benjaminbrgs requested changes
I've suggested some changes but it works perfectly 👌🏼

2023-02-14 13:17 UTC, benjaminbrgs commented on src/components/organisms/AddSkilListSelector.tsx
> +  const [debouncedSearchValue] = useDebounce(search, 500);
And then delete it

2023-02-14 13:17 UTC, benjaminbrgs commented on src/components/organisms/AddSkilListSelector.tsx
> +    variables: { search: `%${debouncedSearchValue}%` },
```suggestion
    variables: { search: `%${search}%` },
```
Here you can use directly the `search` prop as useDebounce is already used in the parent component.

2023-02-14 13:17 UTC, benjaminbrgs commented on src/graphql/queries/skills.ts
> +export const SEARCH_SKILLS_VERIFIED = gql`
There's already the `GET_ALL_VERIFIED_SKILL` query with a search value, maybe we can use it ?

2023-02-14 13:17 UTC, benjaminbrgs commented on src/components/organisms/AddSkilListSelector.tsx
> +    variables: { search: `%${debouncedSearchValue}%` },
This also avoid a delay in the refresh of result number in other categories

2023-02-15 09:29 UTC, benjaminbrgs approved these changes

2023-02-15 09:45 UTC, merged